// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrvQIYrtrFi9z38yWHMz0Es096cAPJu8',
    appId: '1:405501310408:web:fa2190a84526c940e8bcfd',
    messagingSenderId: '405501310408',
    projectId: 'message-bhavishya',
    authDomain: 'message-bhavishya.firebaseapp.com',
    storageBucket: 'message-bhavishya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmn3VPGd9inOxCqPY5KmAYEDPZmQE-Rjc',
    appId: '1:405501310408:android:e5a6ad31ae25e5dfe8bcfd',
    messagingSenderId: '405501310408',
    projectId: 'message-bhavishya',
    storageBucket: 'message-bhavishya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MD3EK6w2x1efPuXTptbL-6MtcD2yiBE',
    appId: '1:405501310408:ios:6fad7bb7b1780f5ee8bcfd',
    messagingSenderId: '405501310408',
    projectId: 'message-bhavishya',
    storageBucket: 'message-bhavishya.appspot.com',
    iosClientId: '405501310408-k6bp97rbubapn7bole88clc5uc515b85.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MD3EK6w2x1efPuXTptbL-6MtcD2yiBE',
    appId: '1:405501310408:ios:6fad7bb7b1780f5ee8bcfd',
    messagingSenderId: '405501310408',
    projectId: 'message-bhavishya',
    storageBucket: 'message-bhavishya.appspot.com',
    iosClientId: '405501310408-k6bp97rbubapn7bole88clc5uc515b85.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
